Repository oleksandrstarov/sigma_js_internship_2021, pull requests merged in 2021-04, with the labels that each got.

#121 Update Movie Banner Component (styles and replace fetch method with axios)
  src/components/MovieBanner.tsx
  src/components/PopularMovie.tsx
  src/styles/MovieBanner.scss
Labels: enhancement

#127 Wrapper for slider 'favourites movies'
  package-lock.json
  package.json
  src/App.scss
  src/components/Home.tsx
  src/components/Layout.tsx
  src/components/WrapperFavorites.tsx
  src/styles/Title.scss
Labels: enhancement

#131 Feature/routing
  src/config/routing.tsx
Labels: enhancement

#128 Feature/pagination
  .idea/codeStyles/codeStyleConfig.xml
  public/images/pagination-arrow.svg
  src/components/Pagination.tsx
  src/styles/Pagination.scss
Labels: enhancement

#136 Implemented Feature/star-rating
  package.json
  src/components/StarRating.tsx
  src/models/index.tsx
  src/styles/StarRating.scss
Labels: enhancement

#150 bugfixes for main(container)
  src/App.scss
  src/components/MovieDetails.tsx
  src/styles/MovieDetails.scss
Labels: bug

#159 Feature/favicon
  public/favicon.ico
  public/index.html
Labels: enhancement

#166 [Movie Details] Refactoring of movie description
  package-lock.json
  src/components/Detail.tsx
  src/components/MovieDetails.tsx
  src/styles/Detail.scss
  src/styles/MovieDetails.scss
Labels: enhancement

#173 Tests for Detail component
  src/components/Detail.test.tsx
Labels: enhancement

#169 Implemented theme switcher for Pages "main" and "movie details"
  package-lock.json
  package.json
  src/App.scss
  src/App.tsx
  src/components/Header.tsx
  src/components/Layout.tsx
  src/components/MovieDetails.tsx
  src/components/SmallInfoCard.tsx
  src/components/ThemeContext.tsx
  src/components/ThemeToggle.tsx
  src/components/WrapperFavorites.tsx
  src/styles/MovieDetails.scss
  src/styles/SmallCardInfo.scss
  src/styles/Title.scss
Labels: enhancement

#179 Testing of Footer Component
  src/components/Footer.test.tsx
Labels: enhancement

#185 Layout tests
  src/components/Layout.test.tsx
Labels: enhancement

#184 Added switching pages without refreshing
  package-lock.json
  src/components/Pagination.tsx
  src/styles/Pagination.scss
Labels: enhancement

#190 Added unit tests and made refactoring for details page
  src/components/MovieDetails.test.tsx
  src/components/MovieDetails.tsx
Labels: enhancement

#167 [Search Field] Added validation (alert messages) for a date range in advanced search
  src/components/SearchField.tsx
  src/styles/SearchField.scss
  src/styles/variables.scss
Labels: enhancement

#203 fixed name of type and method
  src/components/SearchResults.tsx
  src/service/api.tsx
Labels: bug

#205 Bug fix/fix img request
  src/components/SmallInfoCard.tsx
Labels: bug

#168 [Preloader] Implement preloader
  public/images/spinner.svg
  src/components/Preloader.tsx
  src/styles/Preloader.scss
  src/styles/variables.scss
Labels: enhancement

#206 Implemented genre redirection
  package-lock.json
  package.json
  src/components/GenreRedirection.tsx
  src/components/MovieDetails.tsx
  src/components/RenderResults.tsx
  src/components/SearchResults.tsx
  src/constants/api.tsx
  src/models/index.tsx
Labels: enhancement

#212 added links on imgs
  src/components/CardInfo.tsx
  src/components/Home.tsx
  src/components/PopularMovie.tsx
  src/components/SmallInfoCard.tsx
  src/styles/CardInfo.scss
  src/styles/SmallCardInfo.scss
Labels: bug, enhancement

#216 Feature/button render results
  src/components/RenderResults.tsx
  src/styles/RenderResults.scss
Labels: enhancement

#197 [Pagination] Added deps to useEffect
  src/components/Pagination.tsx
Labels: enhancement

#201 [Pagination] Added one more case to switch
  src/components/Pagination.tsx
Labels: bug

#198 [Favorites] Added pagination
  package-lock.json
  src/components/Favorites.tsx
  src/components/Pagination.tsx
  src/service/api.tsx
Labels: enhancement

#193 Implemented ready version of theme switcher for all pages
  package-lock.json
  src/components/CardInfo.tsx
  src/components/PopularMovie.tsx
  src/components/SearchField.tsx
  src/components/Title.tsx
  src/components/WrapperFavorites.tsx
  src/styles/CardInfo.scss
  src/styles/MovieBanner.scss
  src/styles/ReadMore.scss
  src/styles/SearchField.scss
  src/styles/Title.scss
  src/styles/variables.scss
Labels: enhancement

#189 Feature/star rating implementation
  package-lock.json
  src/App.tsx
  src/components/CardInfo.tsx
  src/components/FavoritesBtn.tsx
  src/components/GenreRedirection.tsx
  src/components/MovieBanner.test.tsx
  src/components/MovieRatingContext.tsx
  src/components/PopularMovie.tsx
  src/components/StarRating.test.tsx
  src/components/StarRating.tsx
  src/models/index.tsx
  src/service/rating.tsx
  src/styles/MovieBanner.scss
Labels: enhancement

#214 Implemented query params for search
  package-lock.json
  src/components/SearchField.tsx
  src/components/SearchResults.tsx
  src/config/routing.tsx
Labels: enhancement

#208 fixed rendere comppnents
  src/components/CardInfo.tsx
  src/styles/CardInfo.scss
  src/styles/RenderResults.scss
Labels: bug

#221 Bugfix/movie banner
  src/components/Home.tsx
  src/components/MovieBanner.tsx
  src/components/PopularMovie.tsx
Labels: bug

#239 added star raiting to details page component
  src/components/MovieDetails.tsx
  src/components/StarRating.tsx
Labels: enhancement

#237 Movie banner test
  src/components/MovieBanner.test.tsx
Labels: enhancement

#235 Implemented Feature/favorites
  src/App.tsx
  src/components/FavoritesBtn.tsx
  src/components/FavoritesContext.tsx
  src/components/MovieRatingContext.tsx
  src/components/PopularMovie.tsx
  src/components/StarRating.tsx
  src/components/WrapperFavorites.tsx
  src/models/index.tsx
Labels: enhancement

#195 [Search Results] Add pagination
  src/components/Pagination.tsx
  src/components/SearchResults.tsx
  src/hooks/useLocationHook.tsx
  src/service/api.tsx
Labels: enhancement

#244 Bugfix/search field
  src/components/SearchField.tsx
Labels: bug

#241 Added Favorite icon to details page component
  package-lock.json
  src/components/MovieDetails.test.tsx
  src/components/MovieDetails.tsx
  src/styles/MovieDetails.scss
Labels: enhancement

#242 Bugfix/movie banner (remove a favorite icon from banner)
  src/components/PopularMovie.tsx
Labels: enhancement

#233 [Breadcrumbs]Changed breadcrumbs logic
  src/components/Breadcrumbs.tsx
Labels: enhancement

#249 [Movie cards] Placeholder for broken img links
  public/images/movie-placeholder.jpg
  src/components/CardInfo.tsx
  src/components/MovieDetails.tsx
  src/components/SmallInfoCard.tsx
  src/service/api.tsx
  src/styles/MovieDetails.scss
  src/styles/variables.scss
Labels: enhancement

#252 [Breadcrumbs] added pathname variable to the dependencies
  src/components/Breadcrumbs.tsx
Labels: bug

#253 [Testing] test coverage of favorite btn component
  src/components/FavoriteBtn.test.tsx
Labels: enhancement

#251 [Movie Details] Fix styles and add query param to link
  src/components/CardInfo.tsx
  src/components/MovieDetails.test.tsx
  src/components/MovieDetails.tsx
  src/components/PopularMovie.tsx
  src/components/SmallInfoCard.tsx
  src/config/routing.tsx
  src/styles/Detail.scss
  src/styles/MovieDetails.scss
Labels: enhancement

#210 added last seens to layout
  src/config/routing.tsx
Labels: enhancement

#218 Feature/update cardinfo with favorite
  src/styles/CardInfo.scss
  src/styles/RenderResults.scss
Labels: enhancement

#223 Feature/settings bar use context
  src/App.tsx
  src/components/SettingsBarContext.tsx
  src/components/StarRating.test.tsx
Labels: enhancement

#227 Feature/wrapper last seen
  src/components/LastSeen.tsx
  src/components/SettingsBar.tsx
  src/components/WrapperLastSeen.tsx
  src/config/routing.tsx
Labels: enhancement

#225 Feature/update home page
  src/components/Home.tsx
  src/components/WrapperPopular.tsx
  src/models/index.tsx
  src/service/api.tsx
Labels: enhancement
